"use client"

import { useEffect, useState } from "react"
import { useTranslations } from "next-intl"
import {
  Receipt, CreditCard, CheckCircle2, Clock, Download, ClipboardList,
} from "lucide-react"
import { useAuthStore } from "@/store/useAuthStore"
import { usePatientMe } from "@/lib/usePatientMe"
import { resolveUhid } from "@/lib/uhid"
import { Bills, patientDueOf, type Bill } from "@/lib/api/bills"
import { cn } from "@/lib/utils"
import { printableHtml } from "@/lib/fileIO"

function downloadBillReceipt(
  patientId: string, uhid: string, invoiceNo: string, date: string,
  title: string, total: number, lines: { desc: string; amount: number }[],
) {
  const html = `
    <div class="info-row">
      <div class="info-item"><span class="info-label">Patient ID</span><span class="info-value">${patientId}</span></div>
      <div class="info-item"><span class="info-label">UHID</span><span class="info-value">${uhid}</span></div>
      <div class="info-item"><span class="info-label">Invoice No.</span><span class="info-value">${invoiceNo}</span></div>
      <div class="info-item"><span class="info-label">Date</span><span class="info-value">${date}</span></div>
    </div>
    <h3>Charges</h3>
    <table><thead><tr><th>Description</th><th style="text-align:right">Amount (₹)</th></tr></thead><tbody>
      ${lines.map((l) => `<tr><td>${l.desc}</td><td style="text-align:right">${l.amount.toLocaleString('en-IN')}</td></tr>`).join('')}
      <tr class="total"><td>Total</td><td style="text-align:right">₹${total.toLocaleString('en-IN')}</td></tr>
    </tbody></table>
    <p class="muted">Tax invoice — system-generated by Umang Hospital.</p>`
  printableHtml(invoiceNo, html)
}

const NO_BILLS: Bill[] = []

export default function PatientBilling() {
  const t = useTranslations('patient')
  const currentUser = useAuthStore(s => s.currentUser)
  const { me } = usePatientMe()
  // Keyed by the patient the rows were fetched for, so switching identity
  // shows an empty list by derivation rather than via a synchronous
  // setState([]) inside the effect below.
  const [fetched, setFetched] = useState<{ forId: string; rows: Bill[] } | null>(null)
  const bills = fetched && fetched.forId === me?.id ? fetched.rows : NO_BILLS

  useEffect(() => {
    if (!me) return
    let cancelled = false
    const forId = me.id
    Bills.byPatient(forId).then((rows) => { if (!cancelled) setFetched({ forId, rows }) })
    return () => { cancelled = true }
  }, [me])

  const name = currentUser?.name ?? me?.name ?? 'Patient'
  const pid = me?.id ?? currentUser?.id ?? 'PT-00000'
  const uhid = me ? resolveUhid(me.id, me.uhid) : undefined

  const billedTotal = bills.reduce((s, b) => s + b.total, 0)
  const insuranceCovered = bills.reduce((s, b) => s + b.insuranceCovered, 0)
  const outstanding = bills.reduce((s, b) => s + Math.max(0, patientDueOf(b) - b.paid), 0)

  return (
    <div className="max-w-3xl mx-auto pb-10 space-y-5">
      <div>
        <h1 className="text-[24px] font-bold text-slate-900 tracking-tight">{t('billing.title')}</h1>
        <p className="text-[13px] text-slate-500 mt-1">{name} · {pid}</p>
      </div>

      {/* Summary tiles */}
      <div className="grid grid-cols-3 gap-3">
        <div className="rounded-2xl bg-white shadow-[0_1px_4px_rgba(15,23,42,0.06),0_8px_28px_rgba(15,23,42,0.05)] p-4">
          <p className="text-[12px] text-slate-400 font-semibold">{t('billing.totalBilled')}</p>
          <p className="text-[20px] font-bold text-slate-900 mt-0.5">₹{billedTotal.toLocaleString('en-IN')}</p>
        </div>
        <div className="rounded-2xl bg-white shadow-[0_1px_4px_rgba(15,23,42,0.06),0_8px_28px_rgba(15,23,42,0.05)] p-4">
          <p className="text-[12px] text-slate-400 font-semibold">{t('billing.insuranceCovered')}</p>
          <p className="text-[20px] font-bold text-[var(--color-accent)] mt-0.5">₹{insuranceCovered.toLocaleString('en-IN')}</p>
        </div>
        <div className="rounded-2xl bg-white shadow-[0_1px_4px_rgba(15,23,42,0.06),0_8px_28px_rgba(15,23,42,0.05)] p-4">
          <p className="text-[12px] text-slate-400 font-semibold">Outstanding</p>
          <p className={cn("text-[20px] font-bold mt-0.5", outstanding > 0 ? "text-amber-600" : "text-green-600")}>₹{outstanding.toLocaleString('en-IN')}</p>
        </div>
      </div>

      {bills.length === 0 ? (
        <div className="rounded-3xl bg-white shadow-[0_1px_4px_rgba(15,23,42,0.06),0_8px_28px_rgba(15,23,42,0.05)] p-10 text-center">
          <Receipt className="h-10 w-10 text-slate-300 mx-auto mb-3" />
          <p className="text-[15px] font-bold text-slate-500">No bills yet</p>
          <p className="text-[13px] text-slate-400 mt-1">Bills settled at the billing desk will appear here.</p>
        </div>
      ) : (
        bills.map((bill) => {
          const due = patientDueOf(bill)
          const balance = Math.max(0, due - bill.paid)
          const status: 'paid' | 'pending' = balance <= 0 ? 'paid' : 'pending'
          return (
            <BillCard
              key={bill.id}
              icon={<ClipboardList className="h-5 w-5 text-[var(--color-accent)]" />} tint="bg-[rgba(238,107,38,0.07)]"
              id={bill.id} date={new Date(bill.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}
              title={bill.payerName ? `Invoice · ${bill.payerName}` : `Invoice · ${bill.payerType}`}
              status={status}
              lines={bill.lines.map(l => ({ desc: `${l.name}${l.qty > 1 ? ` × ${l.qty}` : ''}`, amount: l.total }))}
              footer={status === 'paid' ? 'Paid' : undefined}
              onDownload={() => downloadBillReceipt(
                pid, uhid ?? resolveUhid(pid), bill.id,
                new Date(bill.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }),
                bill.payerName ? `Invoice · ${bill.payerName}` : `Invoice · ${bill.payerType}`,
                due, bill.lines.map(l => ({ desc: `${l.name}${l.qty > 1 ? ` × ${l.qty}` : ''}`, amount: l.total })),
              )}
            />
          )
        })
      )}
    </div>
  )
}

type Line = { desc: string; amount: number }
function BillCard({
  icon, tint, id, date, title, status, lines, footer, onDownload,
}: {
  icon: React.ReactNode; tint: string; id: string; date: string; title: string
  status: 'paid' | 'pending'; lines: Line[]; footer?: string; onDownload: () => void
}) {
  const total = lines.reduce((s, l) => s + l.amount, 0)
  return (
    <div className={cn("rounded-3xl bg-white shadow-[0_1px_4px_rgba(15,23,42,0.06),0_8px_28px_rgba(15,23,42,0.05)] p-5", status === 'pending' && "ring-1 ring-amber-200")}>
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-3">
          <span className={cn("h-10 w-10 rounded-2xl flex items-center justify-center flex-shrink-0", tint)}>{icon}</span>
          <div>
            <p className="text-[15px] font-bold text-slate-900">{title}</p>
            <p className="text-[12px] text-slate-500 flex items-center gap-1"><Clock className="h-3 w-3" /> {id} · {date}</p>
          </div>
        </div>
        <span className={cn("text-[12px] font-bold px-2.5 py-1 rounded-full flex-shrink-0", status === 'paid' ? 'bg-green-50 text-green-700' : 'bg-amber-50 text-amber-600')}>
          {status === 'paid' ? '✓ Paid' : 'Pending'}
        </span>
      </div>

      <div className="rounded-2xl bg-slate-50 p-4 space-y-2">
        {lines.map((l, i) => (
          <div key={i} className="flex justify-between text-[13px]">
            <span className="text-slate-500">{l.desc}</span>
            <span className="font-semibold text-slate-800">₹{l.amount.toLocaleString('en-IN')}</span>
          </div>
        ))}
        <div className="border-t border-slate-200 pt-2 flex justify-between font-bold">
          <span className="text-slate-900">Total</span>
          <span className="text-[var(--color-accent)]">₹{total.toLocaleString('en-IN')}</span>
        </div>
      </div>

      <div className="mt-3 flex items-center justify-between gap-2">
        {status === 'paid' ? (
          <span className="text-[12.5px] text-green-700 flex items-center gap-1.5"><CheckCircle2 className="h-4 w-4" /> {footer ?? 'Payment successful'}</span>
        ) : (
          <span className="text-[12.5px] text-amber-600 flex items-center gap-1.5"><CreditCard className="h-4 w-4" /> ₹{total.toLocaleString('en-IN')} due</span>
        )}
        <button onClick={onDownload} className="text-[12.5px] font-semibold text-slate-600 flex items-center gap-1.5 hover:text-slate-900 cursor-pointer"><Download className="h-3.5 w-3.5" /> Receipt</button>
      </div>
    </div>
  )
}
