// AUTO-GENERATED by scripts/i18n-barrel.mjs — do not edit by hand.
import n0 from './abha.json'
import n1 from './admin.json'
import n2 from './admission.json'
import n3 from './ai.json'
import n4 from './ambulance.json'
import n5 from './audit.json'
import n6 from './billing.json'
import n7 from './bloodbank.json'
import n8 from './bmw.json'
import n9 from './checkin.json'
import n10 from './cmo.json'
import n11 from './common.json'
import n12 from './consent.json'
import n13 from './cssd.json'
import n14 from './dietary.json'
import n15 from './discharge.json'
import n16 from './discovery.json'
import n17 from './doctor.json'
import n18 from './emergency.json'
import n19 from './family-track.json'
import n20 from './feedback.json'
import n21 from './housekeeping.json'
import n22 from './hr.json'
import n23 from './insurance.json'
import n24 from './intake.json'
import n25 from './inventory.json'
import n26 from './journey.json'
import n27 from './lab.json'
import n28 from './labs.json'
import n29 from './landing.json'
import n30 from './mortuary.json'
import n31 from './nav.json'
import n32 from './notify.json'
import n33 from './nurse.json'
import n34 from './orderSets.json'
import n35 from './ot.json'
import n36 from './p.json'
import n37 from './patient.json'
import n38 from './pharmacy.json'
import n39 from './quality.json'
import n40 from './radiology.json'
import n41 from './reception.json'
import n42 from './roles.json'
import n43 from './secretary.json'
import n44 from './ui.json'
import n45 from './vendor-manager.json'

const messages = {
  "abha": n0,
  "admin": n1,
  "admission": n2,
  "ai": n3,
  "ambulance": n4,
  "audit": n5,
  "billing": n6,
  "bloodbank": n7,
  "bmw": n8,
  "checkin": n9,
  "cmo": n10,
  "common": n11,
  "consent": n12,
  "cssd": n13,
  "dietary": n14,
  "discharge": n15,
  "discovery": n16,
  "doctor": n17,
  "emergency": n18,
  "family-track": n19,
  "feedback": n20,
  "housekeeping": n21,
  "hr": n22,
  "insurance": n23,
  "intake": n24,
  "inventory": n25,
  "journey": n26,
  "lab": n27,
  "labs": n28,
  "landing": n29,
  "mortuary": n30,
  "nav": n31,
  "notify": n32,
  "nurse": n33,
  "orderSets": n34,
  "ot": n35,
  "p": n36,
  "patient": n37,
  "pharmacy": n38,
  "quality": n39,
  "radiology": n40,
  "reception": n41,
  "roles": n42,
  "secretary": n43,
  "ui": n44,
  "vendor-manager": n45,
} as const

export default messages
