// Regenerates messages/<locale>/index.ts barrels from the per-namespace JSON files.
// Run after adding/removing any messages/<locale>/<namespace>.json. Parallel-safe:
// agents drop namespace JSON files; this regenerates the merged barrel once.
import { readdirSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', 'messages')

for (const locale of ['en', 'hi']) {
  const dir = join(root, locale)
  const files = readdirSync(dir).filter(f => f.endsWith('.json')).sort()
  const ns = files.map(f => f.replace(/\.json$/, ''))
  const imports = ns.map((n, i) => `import n${i} from './${n}.json'`).join('\n')
  const entries = ns.map((n, i) => `  ${JSON.stringify(n)}: n${i},`).join('\n')
  const out = `// AUTO-GENERATED by scripts/i18n-barrel.mjs — do not edit by hand.\n${imports}\n\nconst messages = {\n${entries}\n} as const\n\nexport default messages\n`
  writeFileSync(join(dir, 'index.ts'), out)
  console.log(`${locale}: ${ns.length} namespaces -> ${ns.join(', ')}`)
}
