// AUTO-GENERATED by scripts/i18n-barrel.mjs — do not edit by hand.
import n0 from './abha.json'
import n1 from './checkin.json'
import n2 from './discovery.json'
import n3 from './doctor.json'
import n4 from './intake.json'
import n5 from './journey.json'
import n6 from './labs.json'
import n7 from './landing.json'
import n8 from './nav.json'
import n9 from './notify.json'
import n10 from './nurse.json'
import n11 from './orderSets.json'
import n12 from './p.json'
import n13 from './patient.json'
import n14 from './pharmacy.json'
import n15 from './reception.json'
import n16 from './ui.json'

const messages = {
  "abha": n0,
  "checkin": n1,
  "discovery": n2,
  "doctor": n3,
  "intake": n4,
  "journey": n5,
  "labs": n6,
  "landing": n7,
  "nav": n8,
  "notify": n9,
  "nurse": n10,
  "orderSets": n11,
  "p": n12,
  "patient": n13,
  "pharmacy": n14,
  "reception": n15,
  "ui": n16,
} as const

export default messages
