// AUTO-GENERATED by scripts/i18n-barrel.mjs — do not edit by hand.
import n0 from './checkin.json'
import n1 from './discovery.json'
import n2 from './doctor.json'
import n3 from './intake.json'
import n4 from './journey.json'
import n5 from './labs.json'
import n6 from './landing.json'
import n7 from './nav.json'
import n8 from './notify.json'
import n9 from './nurse.json'
import n10 from './orderSets.json'
import n11 from './p.json'
import n12 from './patient.json'
import n13 from './pharmacy.json'
import n14 from './reception.json'
import n15 from './ui.json'

const messages = {
  "checkin": n0,
  "discovery": n1,
  "doctor": n2,
  "intake": n3,
  "journey": n4,
  "labs": n5,
  "landing": n6,
  "nav": n7,
  "notify": n8,
  "nurse": n9,
  "orderSets": n10,
  "p": n11,
  "patient": n12,
  "pharmacy": n13,
  "reception": n14,
  "ui": n15,
} as const

export default messages
